name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3  # Replace with your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: |
          mkdir -p build
          go build -o build/ ./...
        env:
          GOROOT: /usr/local/go

      - name: Run tests
        run: go test -v ./...
