name: Build and Test Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'  # Adjust Go version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Build the application
      - name: Build the application
        run: go build -v ./...

      # Step 5: Run tests
      - name: Run tests
        run: go test -v ./...

      # Step 6: Upload test results (optional)
      - name: Upload test results
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-report.txt
        run: go test ./... > ./test-report.txt
