image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)   # Format code
    - go vet $(go list ./... | grep -v /vendor/)   # Run static analysis
    - go test -v ./...                             # Run all tests with verbose output
  artifacts:
    reports:
      junit: test-results.xml
  cache:
    paths:
      - go.sum
      - go.mod
      - vendor/

compile:
  stage: build
  script:
    - mkdir -p herbarium                            # Create output directory for herbarium
    - go build -o herbarium ./...                   # Build all binaries into the herbarium directory
  artifacts:
    paths:
      - herbarium                                   # Save built binaries for later stages

deploy:
  stage: deploy
  script: echo "Define your deployment script here!"
  environment: production
  dependencies:
    - compile
  when: manual
